### ISSUE TITLE
offsetIMU problem

### ISSUE THREAD

**Issue by zoldaten** [mdleiton/MPU9255#2]
g++ offsetIMU.cpp -lwiringPi -o offsetIMU gives a error:

offsetIMU.cpp:57:3: error: ‘myfile’ does not name a type
   myfile.txt << giro_x << "," << giro_y << "," << giro_z << "," << acc_x << "," << acc_y << "," << acc_z * conversion_acce << endl;
   ^~~~~~
offsetIMU.cpp:58:3: error: ‘myfile’ does not name a type
   myfile.close();
   ^~~~~~
offsetIMU.cpp:60:3: error: expected unqualified-id before ‘return’
   return 0;
   ^~~~~~

**Comment by mdleiton** [comment]
FIXED. I updated the repository.
