### ISSUE TITLE
No Compass Readings

### ISSUE THREAD

**Issue by ChrisHexapod** [mdleiton/MPU9255#4]
Hi,

I'm unsure if you are still maintaining the project. However, it appears the running your node will not really return any mag data. The reason being, that you have to use a bypass to enable the mag.  Attached you'll find an update version of the code that solves that problem, and as a benfit works also for the MPU9250 :-)

[MPU_9255_node.cpp.txt](https://github.com/mdleiton/MPU9255/files/7828962/MPU_9255_node.cpp.txt)

Cheers

 Chris

**Comment by sskorol** [comment]
@ChrisHexapod it works with Waveshare 10 DOF IMU (C), thanks!

**Comment by mdleiton** [comment]
@ChrisHexapod   Thanks
